flowchart LR
%% generated in 0.01s
    subgraph examples__run_examples
        examples__run_examples__run_example["run_example"]
        examples__run_examples__main["main"]
    end
    subgraph examples__scientific_calculator_demo
        examples__scientific_calculator_demo__main["main"]
    end
    subgraph examples__scientific_calculator_demo2
        examples__scientific_calculator_demo2__main["main"]
        examples__scientific_calculator_demo2__print_code["print_code"]
    end
    subgraph examples__web_app_calculator
        examples__web_app_calculator__run__main["main"]
    end
    subgraph examples__web_app_dashboard
        examples__web_app_dashboard__run__main["main"]
    end
    subgraph scripts__check_doc_links
        scripts__check_doc_links___is_external["_is_external"]
        scripts__check_doc_links___markdown_files["_markdown_files"]
        scripts__check_doc_links___targets["_targets"]
        scripts__check_doc_links___resolve["_resolve"]
        scripts__check_doc_links__check_links["check_links"]
        scripts__check_doc_links___anchors["_anchors"]
        scripts__check_doc_links__main["main"]
        scripts__check_doc_links___slug["_slug"]
    end
    subgraph src__nexu
        src__nexu__cinema_history__restore_history_checkpoint["restore_history_checkpoint"]
        src__nexu__cinema_publish___generate_markpact_export["_generate_markpact_export"]
        src__nexu__cinema_server___open_browser["_open_browser"]
        src__nexu__cinema_projects___write_seed_variants["_write_seed_variants"]
        src__nexu__runtime___read_fixture["_read_fixture"]
        src__nexu__cinema_publish___create_service_entry["_create_service_entry"]
        src__nexu__cinema_policy__cinema_model_label["cinema_model_label"]
        src__nexu__llm__call_litellm_json["call_litellm_json"]
        src__nexu__cinema_projects___resolve_source_cinema["_resolve_source_cinema"]
        src__nexu__orchestrate__offline_orchestration_from_context["offline_orchestration_from_con"]
        src__nexu__cinema_offline_options___numpad_rows["_numpad_rows"]
        src__nexu__cinema_publish__publish_project_service["publish_project_service"]
        src__nexu__llm___extract_content["_extract_content"]
        src__nexu__cinema_history___refresh_policy_snapshot["_refresh_policy_snapshot"]
        src__nexu__journal__journal_path["journal_path"]
        src__nexu__cinema_policy___process_keep_delete_entries["_process_keep_delete_entries"]
        src__nexu__iterate__iterate_capsule["iterate_capsule"]
        src__nexu__cinema_history___load_index["_load_index"]
        src__nexu__export_prompt__export_iteration_prompt["export_iteration_prompt"]
        src__nexu__mcp_server__run_mcp_stdio["run_mcp_stdio"]
        src__nexu__cli__capsule_drift["capsule_drift"]
        src__nexu__cinema_baseline_contracts__calculator_baseline_contracts["calculator_baseline_contracts"]
        src__nexu__cinema_history__history_dir["history_dir"]
        src__nexu__cinema_offline_options___numpad_from_policy["_numpad_from_policy"]
        src__nexu__cinema_offline_options___expanded_excess_row["_expanded_excess_row"]
        src__nexu__review___markdown_review_prompt["_markdown_review_prompt"]
        src__nexu__cli___print_yaml["_print_yaml"]
        src__nexu__journal__read_journal["read_journal"]
        src__nexu__cinema_history__list_history_checkpoints["list_history_checkpoints"]
        src__nexu__cinema___cinema_template_text["_cinema_template_text"]
        src__nexu__cli__capsule_blueprint["capsule_blueprint"]
        src__nexu__cinema_markpact__build_markpact_readme["build_markpact_readme"]
        src__nexu__cli__capsule_plan["capsule_plan"]
        src__nexu__verify___scan_capsule_contracts["_scan_capsule_contracts"]
        src__nexu__cinema_policy__verify_capsule_workspace["verify_capsule_workspace"]
        src__nexu__cinema_server___template_text["_template_text"]
        src__nexu__cinema_projects__find_nexu_repo_root["find_nexu_repo_root"]
        src__nexu__cinema_policy__sync_option_previews_from_workspace["sync_option_previews_from_work"]
        src__nexu__cinema__format_intract_v1_line["format_intract_v1_line"]
        src__nexu__mcp_server___rpc_initialize["_rpc_initialize"]
        src__nexu__plan___contract_summary["_contract_summary"]
        src__nexu__cinema_history___write_index["_write_index"]
        src__nexu__cinema__build_intract_policy_snapshot["build_intract_policy_snapshot"]
        src__nexu__cinema_publish___save_registry["_save_registry"]
        src__nexu__cli__capsule_create["capsule_create"]
        src__nexu__cinema_publish__services_root["services_root"]
        src__nexu__cinema_projects__activate_example_project["activate_example_project"]
        src__nexu__cinema___render_cinema_template["_render_cinema_template"]
        src__nexu__cli__capsule_promote["capsule_promote"]
        src__nexu__orchestrate___render_orchestration_markdown["_render_orchestration_markdown"]
        src__nexu__mcp_server___resource_list["_resource_list"]
        src__nexu__cinema_server___available_port["_available_port"]
        src__nexu__cinema_policy___proposal_kind_and_element["_proposal_kind_and_element"]
        src__nexu__verify___check_baseline_lock["_check_baseline_lock"]
        src__nexu__cinema_baseline_contracts__ensure_capsule_intract_yaml["ensure_capsule_intract_yaml"]
        src__nexu__cinema_server___litellm_available["_litellm_available"]
        src__nexu__cinema_offline_options___policy_constrained["_policy_constrained"]
        src__nexu__cinema_policy__policy_ledger_path["policy_ledger_path"]
        src__nexu__cinema_policy__manifest_paths_from_snapshot["manifest_paths_from_snapshot"]
        src__nexu__cinema_offline_options___option_shell["_option_shell"]
        src__nexu__intract_adapter___ensure_intract_on_path["_ensure_intract_on_path"]
        src__nexu__verify___contains_patterns["_contains_patterns"]
        src__nexu__runtime__build_capsule_runtime["build_capsule_runtime"]
        src__nexu__cli__mcp_serve["mcp_serve"]
        src__nexu__mcp_server___prompt_get["_prompt_get"]
        src__nexu__promote___promotion_map["_promotion_map"]
        src__nexu__cinema_policy__enforce_deletes_on_option_previews["enforce_deletes_on_option_prev"]
        src__nexu__cinema_offline_options___trig_row["_trig_row"]
        src__nexu__config__load_env_files["load_env_files"]
        src__nexu__mcp_server___apply_promotion_from_mcp["_apply_promotion_from_mcp"]
        src__nexu__cinema_baseline_contracts___contract["_contract"]
        src__nexu__cinema_history__ensure_initial_checkpoint["ensure_initial_checkpoint"]
        src__nexu__intract_adapter__check_intract_policy["check_intract_policy"]
        src__nexu__cinema_publish___write_service_readme["_write_service_readme"]
        src__nexu__cinema_offline_options___hints_text["_hints_text"]
        src__nexu__cinema_history__save_history_checkpoint["save_history_checkpoint"]
        src__nexu__files__matches_any["matches_any"]
        src__nexu__mcp_server___read_resource["_read_resource"]
        src__nexu__cinema_baseline_contracts__is_calculator_capsule["is_calculator_capsule"]
        src__nexu__cli__capsule_status_command["capsule_status_command"]
        src__nexu__mcp_server___result_content["_result_content"]
        src__nexu__cinema_offline_options__write_goal_options_offline["write_goal_options_offline"]
        src__nexu__files__is_text_file["is_text_file"]
        src__nexu__cinema_offline_options___chemical_shell["_chemical_shell"]
        src__nexu__cinema_history___build_label["_build_label"]
        src__nexu__verify___check_output_presence["_check_output_presence"]
        src__nexu__mcp_server___prompts_list["_prompts_list"]
        src__nexu__cinema_history__history_index_path["history_index_path"]
        src__nexu__cinema_publish__list_published_services["list_published_services"]
        src__nexu__cinema_offline_options__build_chemical_option_html["build_chemical_option_html"]
        src__nexu__cinema___start_cinema_server["_start_cinema_server"]
        src__nexu__files__rel["rel"]
        src__nexu__cli__capsule_runtime["capsule_runtime"]
        src__nexu__cinema_policy__normalize_proposals_for_ledger["normalize_proposals_for_ledger"]
        src__nexu__cinema_policy__cinema_dir_for["cinema_dir_for"]
        src__nexu__cli__freeze["freeze"]
        src__nexu__cinema_history___ledger_snapshot["_ledger_snapshot"]
        src__nexu__cinema_scripts__finalize_cinema_html["finalize_cinema_html"]
        src__nexu__cinema_history__ledger_archive_for_display["ledger_archive_for_display"]
        src__nexu__cinema_publish___service_alive["_service_alive"]
        src__nexu__cinema_policy__option_previews_are_distinct["option_previews_are_distinct"]
        src__nexu__cinema_publish___pick_port["_pick_port"]
        src__nexu__verify___check_forbidden_secret["_check_forbidden_secret"]
        src__nexu__capsule__load_capsule["load_capsule"]
        src__nexu__cinema_projects___copy_cinema_files["_copy_cinema_files"]
        src__nexu__cinema_scripts__apply_spatial_deletes_to_html["apply_spatial_deletes_to_html"]
        src__nexu__cinema_server___try_spawn_on_port["_try_spawn_on_port"]
        src__nexu__capsule__save_capsule["save_capsule"]
        src__nexu__cinema_publish__start_published_service["start_published_service"]
        src__nexu__intract_adapter___sibling_intract_src["_sibling_intract_src"]
        src__nexu__mcp_server___tool_map["_tool_map"]
        src__nexu__cinema_offline_options___btn["_btn"]
        src__nexu__mcp_server___rpc_handlers["_rpc_handlers"]
        src__nexu__blueprint__build_blueprint["build_blueprint"]
        src__nexu__cinema_server__start_cinema_player_server["start_cinema_player_server"]
        src__nexu__cinema_offline_options__is_chemical_goal["is_chemical_goal"]
        src__nexu__cinema_policy___process_proposed_contracts["_process_proposed_contracts"]
        src__nexu__llm__call_litellm_review["call_litellm_review"]
        src__nexu__cinema_policy__validate_intract_artifact["validate_intract_artifact"]
        src__nexu__orchestrate__build_capsule_orchestration["build_capsule_orchestration"]
        src__nexu__review__build_review_packet["build_review_packet"]
        src__nexu__cinema_policy__propose_llm_for_stage["propose_llm_for_stage"]
        src__nexu__cinema_offline_options___keep_ids_lower["_keep_ids_lower"]
        src__nexu__cinema_baseline_contracts__merge_calculator_baselines["merge_calculator_baselines"]
        src__nexu__cinema_publish___http_ok["_http_ok"]
        src__nexu__cinema_policy__ensure_intract_on_path["ensure_intract_on_path"]
        src__nexu__cinema_policy__effective_ui_constraints_from_ledger["effective_ui_constraints_from_"]
        src__nexu__llm__offline_review_from_status["offline_review_from_status"]
        src__nexu__bundle___should_include["_should_include"]
        src__nexu__cinema__generate_cinema_player["generate_cinema_player"]
        src__nexu__verify___check_forbidden_write["_check_forbidden_write"]
        src__nexu__cinema_publish__stop_published_service["stop_published_service"]
        src__nexu__paths__snapshots_dir["snapshots_dir"]
        src__nexu__cinema___contract_to_public_dict["_contract_to_public_dict"]
        src__nexu__cinema_publish___port_open["_port_open"]
        src__nexu__cli__capsule_journal["capsule_journal"]
        src__nexu__cinema_scripts__write_cinema_inject_files["write_cinema_inject_files"]
        src__nexu__cinema_publish___load_registry["_load_registry"]
        src__nexu__cinema_publish___slug_service_id["_slug_service_id"]
        src__nexu__cinema_offline_options___policy_screen_text["_policy_screen_text"]
        src__nexu__cinema_policy__ensure_option_previews_from_stages["ensure_option_previews_from_st"]
        src__nexu__cinema_publish___allocate_service_port["_allocate_service_port"]
        src__nexu__verify___text["_text"]
        src__nexu__cinema_policy__policy_snapshot_path["policy_snapshot_path"]
        src__nexu__paths__ensure_project_dirs["ensure_project_dirs"]
        src__nexu__llm___strip_fences["_strip_fences"]
        src__nexu__cinema_server___render_server_script["_render_server_script"]
        src__nexu__cinema_policy__stage_files_are_distinct["stage_files_are_distinct"]
        src__nexu__intract_adapter___policy_findings["_policy_findings"]
        src__nexu__cinema_offline_options___mandatory_trig["_mandatory_trig"]
        src__nexu__promote__build_promotion_plan["build_promotion_plan"]
        src__nexu__cli__capsule_orchestrate["capsule_orchestrate"]
        src__nexu__cli__init["init"]
        src__nexu__paths__capsule_dir["capsule_dir"]
        src__nexu__cli__capsule_list["capsule_list"]
        src__nexu__verify__verify_capsule["verify_capsule"]
        src__nexu__orchestrate___contract_dicts["_contract_dicts"]
        src__nexu__cinema_publish___registry_path["_registry_path"]
        src__nexu__cinema_policy__propose_ui_delta_contract_dicts["propose_ui_delta_contract_dict"]
        src__nexu__cinema_policy__load_policy_snapshot["load_policy_snapshot"]
        src__nexu__cinema_policy__load_effective_ui_constraints["load_effective_ui_constraints"]
        src__nexu__cinema_publish___register_service["_register_service"]
        src__nexu__cinema_scripts__repair_cinema_html_files["repair_cinema_html_files"]
        src__nexu__cinema_publish___prepare_service_directory["_prepare_service_directory"]
        src__nexu__orchestrate__build_orchestration_context["build_orchestration_context"]
        src__nexu__export_prompt___cinema_policy_ledger_block["_cinema_policy_ledger_block"]
        src__nexu__files__collect_files["collect_files"]
        src__nexu__mcp_server__call_tool["call_tool"]
        src__nexu__cli__capsule_review["capsule_review"]
        src__nexu__cinema_offline_options___numpad_token_btn["_numpad_token_btn"]
        src__nexu__cinema_offline_options___cinema_is_calculator["_cinema_is_calculator"]
        src__nexu__cinema__write_intract_policy_files["write_intract_policy_files"]
        src__nexu__cinema_policy__apply_ledger_from_cinema["apply_ledger_from_cinema"]
        src__nexu__report__build_capsule_report["build_capsule_report"]
        src__nexu__bundle__build_capsule_bundle["build_capsule_bundle"]
        src__nexu__cinema__write_cinema_nexu_hooks["write_cinema_nexu_hooks"]
        src__nexu__cinema_policy__normalize_manifest_target["normalize_manifest_target"]
        src__nexu__intract_adapter___result_status["_result_status"]
        src__nexu__paths__project_root["project_root"]
        src__nexu__cinema_policy__append_policy_ledger_entry["append_policy_ledger_entry"]
        src__nexu__cli__capsule_diff["capsule_diff"]
        src__nexu__cinema_publish___refresh_service_status["_refresh_service_status"]
        src__nexu__paths__nexu_dir["nexu_dir"]
        src__nexu__cinema_policy___build_constraint_result["_build_constraint_result"]
        src__nexu__paths__capsules_dir["capsules_dir"]
        src__nexu__mcp_server__handle_mcp_message["handle_mcp_message"]
        src__nexu__cli__capsule_verify["capsule_verify"]
        src__nexu__cinema_policy___normalize_html_body["_normalize_html_body"]
        src__nexu__cinema_history___copy_checkpoint_files["_copy_checkpoint_files"]
        src__nexu__init_project__init_project["init_project"]
        src__nexu__cinema_policy___html_files_distinct["_html_files_distinct"]
        src__nexu__orchestrate__build_orchestration_prompt["build_orchestration_prompt"]
        src__nexu__verify___check_source_files_presence["_check_source_files_presence"]
        src__nexu__cinema_policy___replace_html_title["_replace_html_title"]
        src__nexu__runtime___collect_fixtures["_collect_fixtures"]
        src__nexu__cli__capsule_bundle["capsule_bundle"]
        src__nexu__cli__capsule_report["capsule_report"]
        src__nexu__config___load_env_file["_load_env_file"]
        src__nexu__cinema_policy__append_iteration_ledger_entry["append_iteration_ledger_entry"]
        src__nexu__cinema_offline_options__build_policy_scientific_option_html["build_policy_scientific_option"]
        src__nexu__journal__append_journal["append_journal"]
        src__nexu__cinema_markpact___escape_markdown_fence["_escape_markdown_fence"]
        src__nexu__capsule__list_capsules["list_capsules"]
        src__nexu__promote__apply_promotion_plan["apply_promotion_plan"]
        src__nexu__cinema_baseline_contracts___line["_line"]
        src__nexu__capsule__create_capsule["create_capsule"]
        src__nexu__cli__capsule_export_prompt["capsule_export_prompt"]
        src__nexu__cinema_policy___process_ledger_entry["_process_ledger_entry"]
        src__nexu__cinema_scripts___delete_match_keys["_delete_match_keys"]
        src__nexu__config__load_config["load_config"]
        src__nexu__cinema_publish___handle_existing_service["_handle_existing_service"]
        src__nexu__cinema_server__start_persistent_http_server["start_persistent_http_server"]
        src__nexu__intract_adapter___finding_for_result["_finding_for_result"]
        src__nexu__cli__capsule_iterate["capsule_iterate"]
        src__nexu__plan__build_iteration_plan["build_iteration_plan"]
        src__nexu__cli___relative_to_root["_relative_to_root"]
        src__nexu__verify___find_term_evidence["_find_term_evidence"]
    end
    subgraph src__vico
        src__vico__diff__diff_capsule["diff_capsule"]
        src__vico__intract___split_csv["_split_csv"]
        src__vico__intract__scan_contracts_in_text["scan_contracts_in_text"]
        src__vico__models__FrozenSnapshot__from_dict["from_dict"]
        src__vico__intract__parse_intract_line["parse_intract_line"]
        src__vico__intract___tokenize_contract["_tokenize_contract"]
        src__vico__git__current_git_sha["current_git_sha"]
        src__vico__status__capsule_status["capsule_status"]
        src__vico__drift__check_source_drift["check_source_drift"]
        src__vico__intract__read_manifest_contracts["read_manifest_contracts"]
        src__vico__models__utc_now["utc_now"]
        src__vico__hashing__sha256_file["sha256_file"]
        src__vico__freeze__freeze_project["freeze_project"]
        src__vico__intract__scan_contracts_in_file["scan_contracts_in_file"]
        src__vico__models__read_yaml["read_yaml"]
        src__vico__models__write_yaml["write_yaml"]
    end
    examples__scientific_calculator_demo__main --> src__nexu__init_project__init_project
    examples__scientific_calculator_demo__main --> src__vico__freeze__freeze_project
    examples__scientific_calculator_demo__main --> src__nexu__capsule__create_capsule
    examples__run_examples__run_example --> src__nexu__init_project__init_project
    examples__run_examples__run_example --> src__vico__freeze__freeze_project
    examples__run_examples__run_example --> src__nexu__capsule__create_capsule
    examples__run_examples__run_example --> src__nexu__plan__build_iteration_plan
    examples__run_examples__run_example --> src__nexu__blueprint__build_blueprint
    examples__run_examples__run_example --> src__nexu__iterate__iterate_capsule
    examples__run_examples__run_example --> src__nexu__runtime__build_capsule_runtime
    examples__run_examples__run_example --> src__nexu__export_prompt__export_iteration_prompt
    examples__run_examples__main --> examples__run_examples__run_example
    examples__scientific_calculator_demo2__main --> examples__scientific_calculator_demo2__print_code
    examples__scientific_calculator_demo2__main --> src__nexu__init_project__init_project
    examples__scientific_calculator_demo2__main --> src__vico__freeze__freeze_project
    examples__scientific_calculator_demo2__main --> src__nexu__capsule__create_capsule
    examples__scientific_calculator_demo2__main --> src__nexu__iterate__iterate_capsule
    examples__web_app_calculator__run__main --> src__nexu__init_project__init_project
    examples__web_app_calculator__run__main --> src__vico__freeze__freeze_project
    examples__web_app_calculator__run__main --> src__nexu__capsule__create_capsule
    examples__web_app_dashboard__run__main --> src__nexu__init_project__init_project
    examples__web_app_dashboard__run__main --> src__vico__freeze__freeze_project
    examples__web_app_dashboard__run__main --> src__nexu__capsule__create_capsule
    src__nexu__runtime___collect_fixtures --> src__nexu__runtime___read_fixture
    src__nexu__runtime__build_capsule_runtime --> src__nexu__capsule__load_capsule
    src__nexu__runtime__build_capsule_runtime --> src__nexu__paths__capsule_dir
    src__nexu__runtime__build_capsule_runtime --> src__nexu__blueprint__build_blueprint
    src__nexu__runtime__build_capsule_runtime --> src__vico__intract__read_manifest_contracts
    src__nexu__runtime__build_capsule_runtime --> src__vico__models__write_yaml
    src__nexu__runtime__build_capsule_runtime --> src__nexu__journal__append_journal
    src__nexu__runtime__build_capsule_runtime --> src__vico__models__utc_now
    src__nexu__init_project__init_project --> src__nexu__paths__ensure_project_dirs
    src__nexu__init_project__init_project --> src__vico__models__write_yaml
    src__nexu__config__load_env_files --> src__nexu__config___load_env_file
    src__nexu__config__load_config --> src__nexu__config__load_env_files
    src__nexu__config__load_config --> src__vico__models__read_yaml
    src__vico__intract__parse_intract_line --> src__vico__intract___tokenize_contract
    src__vico__intract__parse_intract_line --> src__vico__intract___split_csv
    src__vico__intract__scan_contracts_in_text --> src__vico__intract__parse_intract_line
    src__vico__intract__scan_contracts_in_file --> src__vico__intract__scan_contracts_in_text
    src__nexu__cli__init --> src__nexu__paths__project_root
    src__nexu__cli__init --> src__nexu__init_project__init_project
    src__nexu__cli__freeze --> src__nexu__paths__project_root
    src__nexu__cli__freeze --> src__vico__freeze__freeze_project
    src__nexu__cli__capsule_create --> src__nexu__paths__project_root
    src__nexu__cli__capsule_create --> src__nexu__capsule__create_capsule
    src__nexu__cli__capsule_create --> src__nexu__blueprint__build_blueprint
    src__nexu__cli__capsule_list --> src__nexu__paths__project_root
    src__nexu__cli__capsule_list --> src__nexu__capsule__list_capsules
    src__nexu__cli__capsule_status_command --> src__nexu__paths__project_root
    src__nexu__cli__capsule_status_command --> src__vico__status__capsule_status
    src__nexu__cli__capsule_iterate --> src__nexu__paths__project_root
    src__nexu__cli__capsule_iterate --> src__nexu__iterate__iterate_capsule
    src__nexu__cli__capsule_iterate --> src__nexu__journal__append_journal
    src__nexu__cli__capsule_iterate --> src__nexu__cinema__generate_cinema_player
    src__nexu__cli__capsule_blueprint --> src__nexu__paths__project_root
    src__nexu__cli__capsule_blueprint --> src__nexu__blueprint__build_blueprint
    src__nexu__cli__capsule_blueprint --> src__nexu__cli___print_yaml
    src__nexu__cli__capsule_export_prompt --> src__nexu__paths__project_root
    src__nexu__cli__capsule_export_prompt --> src__nexu__export_prompt__export_iteration_prompt
    src__nexu__cli__capsule_export_prompt --> src__nexu__cli___relative_to_root
    src__nexu__cli__capsule_diff --> src__nexu__paths__project_root
    src__nexu__cli__capsule_diff --> src__vico__diff__diff_capsule
    src__nexu__cli__capsule_drift --> src__nexu__paths__project_root
    src__nexu__cli__capsule_drift --> src__vico__drift__check_source_drift
    src__nexu__cli__capsule_verify --> src__nexu__paths__project_root
    src__nexu__cli__capsule_verify --> src__nexu__verify__verify_capsule
    src__nexu__cli__capsule_plan --> src__nexu__paths__project_root
    src__nexu__cli__capsule_plan --> src__nexu__plan__build_iteration_plan
    src__nexu__cli__capsule_plan --> src__nexu__cli___print_yaml
    src__nexu__cli__capsule_runtime --> src__nexu__paths__project_root
    src__nexu__cli__capsule_runtime --> src__nexu__runtime__build_capsule_runtime
    src__nexu__cli__capsule_runtime --> src__nexu__cli___relative_to_root
    src__nexu__cli__capsule_report --> src__nexu__paths__project_root
    src__nexu__cli__capsule_report --> src__nexu__report__build_capsule_report
    src__nexu__cli__capsule_report --> src__nexu__cli___relative_to_root
    src__nexu__cli__capsule_journal --> src__nexu__paths__project_root
    src__nexu__cli__capsule_journal --> src__nexu__journal__read_journal
    src__nexu__cli__capsule_orchestrate --> src__nexu__paths__project_root
    src__nexu__cli__capsule_orchestrate --> src__nexu__orchestrate__build_capsule_orchestration
    src__nexu__cli__capsule_review --> src__nexu__paths__project_root
    src__nexu__cli__capsule_review --> src__nexu__review__build_review_packet
    src__nexu__cli__capsule_bundle --> src__nexu__paths__project_root
    src__nexu__cli__capsule_bundle --> src__nexu__bundle__build_capsule_bundle
    src__nexu__cli__capsule_bundle --> src__nexu__cli___relative_to_root
    src__nexu__cli__capsule_promote --> src__nexu__paths__project_root
    src__nexu__cli__capsule_promote --> src__nexu__promote__build_promotion_plan
    src__nexu__cli__capsule_promote --> src__nexu__promote__apply_promotion_plan
    src__nexu__cli__mcp_serve --> src__nexu__paths__project_root
    src__nexu__cli__mcp_serve --> src__nexu__mcp_server__run_mcp_stdio
    src__nexu__cinema_server___render_server_script --> src__nexu__cinema_server___template_text
    src__nexu__cinema_server___available_port --> src__nexu__cinema_server___try_spawn_on_port
    src__nexu__cinema_server__start_persistent_http_server --> src__nexu__config__load_env_files
    src__nexu__cinema_server__start_persistent_http_server --> src__nexu__cinema_server___render_server_script
    src__nexu__cinema_server__start_persistent_http_server --> src__nexu__cinema_server___available_port
    src__nexu__cinema_server__start_persistent_http_server --> src__nexu__config__load_config
    src__nexu__cinema_server__start_persistent_http_server --> src__nexu__cinema_server___litellm_available
    src__nexu__cinema_server__start_cinema_player_server --> src__nexu__cinema_server__start_persistent_http_server
    src__nexu__cinema_server__start_cinema_player_server --> src__nexu__cinema_server___open_browser
    src__nexu__llm__call_litellm_json --> src__nexu__llm___strip_fences
    src__nexu__llm__call_litellm_json --> src__nexu__llm___extract_content
    src__nexu__llm__call_litellm_review --> src__nexu__llm__call_litellm_json
    src__nexu__bundle___should_include --> src__nexu__files__rel
    src__nexu__bundle__build_capsule_bundle --> src__nexu__paths__capsule_dir
    src__nexu__bundle__build_capsule_bundle --> src__vico__models__write_yaml
    src__nexu__bundle__build_capsule_bundle --> src__nexu__journal__append_journal
    src__nexu__bundle__build_capsule_bundle --> src__vico__models__utc_now
    src__nexu__intract_adapter___ensure_intract_on_path --> src__nexu__intract_adapter___sibling_intract_src
    src__nexu__intract_adapter___finding_for_result --> src__nexu__intract_adapter___result_status
    src__nexu__intract_adapter__check_intract_policy --> src__nexu__intract_adapter___ensure_intract_on_path
    src__nexu__intract_adapter__check_intract_policy --> src__nexu__files__rel
    src__nexu__intract_adapter__check_intract_policy --> src__nexu__intract_adapter___policy_findings
    src__vico__freeze__freeze_project --> src__nexu__paths__ensure_project_dirs
    src__vico__freeze__freeze_project --> src__vico__models__write_yaml
    src__vico__freeze__freeze_project --> src__nexu__files__collect_files
    src__vico__freeze__freeze_project --> src__vico__git__current_git_sha
    src__vico__freeze__freeze_project --> src__nexu__paths__snapshots_dir
    src__vico__freeze__freeze_project --> src__nexu__files__rel
    src__nexu__review__build_review_packet --> src__nexu__config__load_config
    src__nexu__review__build_review_packet --> src__nexu__paths__capsule_dir
    src__nexu__review__build_review_packet --> src__nexu__verify__verify_capsule
    src__nexu__review__build_review_packet --> src__vico__diff__diff_capsule
    src__nexu__review__build_review_packet --> src__vico__drift__check_source_drift
    src__nexu__review__build_review_packet --> src__nexu__blueprint__build_blueprint
    src__nexu__review__build_review_packet --> src__nexu__export_prompt__export_iteration_prompt
    src__nexu__review__build_review_packet --> src__nexu__llm__offline_review_from_status
    src__nexu__review__build_review_packet --> src__nexu__review___markdown_review_prompt
    src__nexu__plan__build_iteration_plan --> src__nexu__capsule__load_capsule
    src__nexu__plan__build_iteration_plan --> src__nexu__paths__capsule_dir
    src__nexu__plan__build_iteration_plan --> src__vico__intract__read_manifest_contracts
    src__nexu__plan__build_iteration_plan --> src__nexu__blueprint__build_blueprint
    src__nexu__plan__build_iteration_plan --> src__nexu__plan___contract_summary
    src__nexu__plan__build_iteration_plan --> src__vico__models__write_yaml
    src__nexu__plan__build_iteration_plan --> src__nexu__journal__append_journal
    src__nexu__blueprint__build_blueprint --> src__nexu__capsule__load_capsule
    src__nexu__blueprint__build_blueprint --> src__nexu__paths__capsule_dir
    src__nexu__blueprint__build_blueprint --> src__vico__intract__read_manifest_contracts
    src__nexu__blueprint__build_blueprint --> src__vico__models__write_yaml
    src__nexu__blueprint__build_blueprint --> src__vico__models__utc_now
    src__nexu__files__collect_files --> src__nexu__files__rel
    src__nexu__files__collect_files --> src__nexu__files__matches_any
    src__nexu__files__collect_files --> src__nexu__files__is_text_file
    src__vico__status__capsule_status --> src__nexu__capsule__load_capsule
    src__vico__status__capsule_status --> src__nexu__paths__capsule_dir
    src__vico__status__capsule_status --> src__vico__diff__diff_capsule
    src__vico__status__capsule_status --> src__vico__models__read_yaml
    src__nexu__iterate__iterate_capsule --> src__nexu__capsule__load_capsule
    src__nexu__iterate__iterate_capsule --> src__nexu__paths__capsule_dir
    src__nexu__iterate__iterate_capsule --> src__nexu__capsule__save_capsule
    src__nexu__iterate__iterate_capsule --> src__vico__models__write_yaml
    src__vico__drift__check_source_drift --> src__nexu__capsule__load_capsule
    src__vico__drift__check_source_drift --> src__vico__models__write_yaml
    src__vico__drift__check_source_drift --> src__vico__hashing__sha256_file
    src__vico__drift__check_source_drift --> src__vico__models__utc_now
    src__vico__drift__check_source_drift --> src__nexu__paths__capsule_dir
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_projects___resolve_source_cinema
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_scripts__write_cinema_inject_files
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_projects__find_nexu_repo_root
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_projects___copy_cinema_files
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_projects___write_seed_variants
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_policy__stage_files_are_distinct
    src__nexu__cinema_projects__activate_example_project --> src__nexu__cinema_policy__ensure_option_previews_from_stages
    src__nexu__cinema_history__history_index_path --> src__nexu__cinema_history__history_dir
    src__nexu__cinema_history___load_index --> src__nexu__cinema_history__history_index_path
    src__nexu__cinema_history___write_index --> src__nexu__cinema_history__history_dir
    src__nexu__cinema_history___write_index --> src__nexu__cinema_history__history_index_path
    src__nexu__cinema_history__save_history_checkpoint --> src__nexu__cinema_history___load_index
    src__nexu__cinema_history__save_history_checkpoint --> src__nexu__cinema_history___copy_checkpoint_files
    src__nexu__cinema_history__save_history_checkpoint --> src__nexu__cinema_history___ledger_snapshot
    src__nexu__cinema_history__list_history_checkpoints --> src__nexu__cinema_history___load_index
    src__nexu__cinema_history__restore_history_checkpoint --> src__nexu__paths__project_root
    src__nexu__cinema_history__restore_history_checkpoint --> src__nexu__cinema_policy__cinema_dir_for
    src__nexu__cinema_history__restore_history_checkpoint --> src__nexu__cinema_history___refresh_policy_snapshot
    src__nexu__cinema_history__restore_history_checkpoint --> src__nexu__cinema_history__history_dir
    src__nexu__cinema_history___refresh_policy_snapshot --> src__nexu__cinema__write_intract_policy_files
    src__nexu__cinema_history__ensure_initial_checkpoint --> src__nexu__cinema_history___load_index
    src__nexu__cinema_history__ensure_initial_checkpoint --> src__nexu__cinema_history__save_history_checkpoint
    src__nexu__cinema_history__ensure_initial_checkpoint --> src__nexu__cinema_history___ledger_snapshot
    src__nexu__cinema_history__ledger_archive_for_display --> src__nexu__cinema_history___ledger_snapshot
    src__nexu__cinema_history__ledger_archive_for_display --> src__nexu__cinema_history___build_label
    src__nexu__export_prompt__export_iteration_prompt --> src__nexu__capsule__load_capsule
    src__nexu__export_prompt__export_iteration_prompt --> src__nexu__paths__capsule_dir
    src__nexu__export_prompt__export_iteration_prompt --> src__vico__intract__read_manifest_contracts
    src__nexu__export_prompt__export_iteration_prompt --> src__nexu__blueprint__build_blueprint
    src__nexu__export_prompt__export_iteration_prompt --> src__vico__diff__diff_capsule
    src__nexu__export_prompt__export_iteration_prompt --> src__nexu__export_prompt___cinema_policy_ledger_block
    src__nexu__paths__snapshots_dir --> src__nexu__paths__nexu_dir
    src__nexu__paths__capsules_dir --> src__nexu__paths__nexu_dir
    src__nexu__paths__capsule_dir --> src__nexu__paths__capsules_dir
    src__nexu__paths__ensure_project_dirs --> src__nexu__paths__nexu_dir
    src__nexu__paths__ensure_project_dirs --> src__nexu__paths__snapshots_dir
    src__nexu__paths__ensure_project_dirs --> src__nexu__paths__capsules_dir
    src__nexu__promote___promotion_map --> src__nexu__files__rel
    src__nexu__promote__build_promotion_plan --> src__nexu__capsule__load_capsule
    src__nexu__promote__build_promotion_plan --> src__nexu__paths__capsule_dir
    src__nexu__promote__build_promotion_plan --> src__nexu__files__collect_files
    src__nexu__promote__build_promotion_plan --> src__nexu__verify__verify_capsule
    src__nexu__promote__build_promotion_plan --> src__vico__drift__check_source_drift
    src__nexu__promote__build_promotion_plan --> src__vico__diff__diff_capsule
    src__nexu__promote__build_promotion_plan --> src__vico__models__write_yaml
    src__nexu__promote__build_promotion_plan --> src__vico__models__utc_now
    src__nexu__promote__build_promotion_plan --> src__nexu__promote___promotion_map
    src__nexu__promote__apply_promotion_plan --> src__nexu__paths__capsule_dir
    src__nexu__orchestrate__build_orchestration_context --> src__nexu__capsule__load_capsule
    src__nexu__orchestrate__build_orchestration_context --> src__nexu__paths__capsule_dir
    src__nexu__orchestrate__build_orchestration_context --> src__vico__intract__read_manifest_contracts
    src__nexu__orchestrate__build_orchestration_context --> src__nexu__plan__build_iteration_plan
    src__nexu__orchestrate__build_orchestration_context --> src__nexu__blueprint__build_blueprint
    src__nexu__orchestrate__build_orchestration_context --> src__nexu__verify__verify_capsule
    src__nexu__orchestrate__build_orchestration_context --> src__vico__diff__diff_capsule
    src__nexu__orchestrate__build_orchestration_context --> src__nexu__orchestrate___contract_dicts
    src__nexu__orchestrate__offline_orchestration_from_context --> src__vico__models__utc_now
    src__nexu__orchestrate__build_capsule_orchestration --> src__nexu__config__load_config
    src__nexu__orchestrate__build_capsule_orchestration --> src__nexu__paths__capsule_dir
    src__nexu__orchestrate__build_capsule_orchestration --> src__nexu__orchestrate__build_orchestration_context
    src__nexu__orchestrate__build_capsule_orchestration --> src__nexu__orchestrate__build_orchestration_prompt
    src__nexu__orchestrate__build_capsule_orchestration --> src__vico__models__write_yaml
    src__nexu__orchestrate__build_capsule_orchestration --> src__nexu__orchestrate___render_orchestration_markdown
    src__vico__models__FrozenSnapshot__from_dict --> src__vico__models__utc_now
    src__vico__diff__diff_capsule --> src__nexu__capsule__load_capsule
    src__vico__diff__diff_capsule --> src__nexu__paths__capsule_dir
    src__vico__diff__diff_capsule --> src__vico__models__write_yaml
    src__vico__diff__diff_capsule --> src__nexu__files__rel
    src__vico__diff__diff_capsule --> src__vico__hashing__sha256_file
    src__nexu__verify___scan_capsule_contracts --> src__vico__intract__read_manifest_contracts
    src__nexu__verify___scan_capsule_contracts --> src__nexu__files__collect_files
    src__nexu__verify___scan_capsule_contracts --> src__vico__intract__scan_contracts_in_file
    src__nexu__verify___contains_patterns --> src__nexu__verify___text
    src__nexu__verify___find_term_evidence --> src__nexu__verify___text
    src__nexu__verify___find_term_evidence --> src__nexu__files__rel
    src__nexu__verify___check_source_files_presence --> src__nexu__files__rel
    src__nexu__verify___check_baseline_lock --> src__vico__diff__diff_capsule
    src__nexu__verify___check_forbidden_write --> src__nexu__verify___contains_patterns
    src__nexu__verify___check_forbidden_secret --> src__nexu__verify___contains_patterns
    src__nexu__verify___check_output_presence --> src__nexu__verify___find_term_evidence
    src__nexu__verify__verify_capsule --> src__nexu__capsule__load_capsule
    src__nexu__verify__verify_capsule --> src__nexu__paths__capsule_dir
    src__nexu__verify__verify_capsule --> src__nexu__verify___scan_capsule_contracts
    src__nexu__verify__verify_capsule --> src__nexu__files__collect_files
    src__nexu__journal__journal_path --> src__nexu__paths__capsule_dir
    src__nexu__journal__read_journal --> src__nexu__journal__journal_path
    src__nexu__journal__read_journal --> src__vico__models__read_yaml
    src__nexu__journal__append_journal --> src__nexu__journal__read_journal
    src__nexu__journal__append_journal --> src__vico__models__write_yaml
    src__nexu__journal__append_journal --> src__vico__models__utc_now
    src__nexu__journal__append_journal --> src__nexu__journal__journal_path
    src__nexu__report__build_capsule_report --> src__nexu__paths__capsule_dir
    src__nexu__report__build_capsule_report --> src__nexu__verify__verify_capsule
    src__nexu__report__build_capsule_report --> src__vico__diff__diff_capsule
    src__nexu__report__build_capsule_report --> src__vico__drift__check_source_drift
    src__nexu__report__build_capsule_report --> src__vico__status__capsule_status
    src__nexu__report__build_capsule_report --> src__nexu__journal__read_journal
    src__nexu__report__build_capsule_report --> src__vico__models__write_yaml
    src__nexu__capsule__create_capsule --> src__nexu__paths__ensure_project_dirs
    src__nexu__capsule__create_capsule --> src__nexu__paths__capsule_dir
    src__nexu__capsule__create_capsule --> src__nexu__files__collect_files
    src__nexu__capsule__create_capsule --> src__vico__models__write_yaml
    src__nexu__capsule__create_capsule --> src__nexu__journal__append_journal
    src__nexu__capsule__list_capsules --> src__nexu__paths__capsules_dir
    src__nexu__capsule__load_capsule --> src__vico__models__read_yaml
    src__nexu__capsule__load_capsule --> src__nexu__paths__capsule_dir
    src__nexu__capsule__save_capsule --> src__vico__models__write_yaml
    src__nexu__capsule__save_capsule --> src__nexu__paths__capsule_dir
    src__nexu__mcp_server___apply_promotion_from_mcp --> src__nexu__promote__build_promotion_plan
    src__nexu__mcp_server___apply_promotion_from_mcp --> src__nexu__promote__apply_promotion_plan
    src__nexu__mcp_server__call_tool --> src__nexu__mcp_server___tool_map
    src__nexu__mcp_server___resource_list --> src__nexu__capsule__list_capsules
    src__nexu__mcp_server___read_resource --> src__vico__status__capsule_status
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server___rpc_initialize
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server___result_content
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server___read_resource
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server___prompt_get
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server__call_tool
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server___resource_list
    src__nexu__mcp_server___rpc_handlers --> src__nexu__mcp_server___prompts_list
    src__nexu__mcp_server__handle_mcp_message --> src__nexu__mcp_server___rpc_handlers
    src__nexu__mcp_server__run_mcp_stdio --> src__nexu__mcp_server__handle_mcp_message
    scripts__check_doc_links___anchors --> scripts__check_doc_links___slug
    scripts__check_doc_links__check_links --> scripts__check_doc_links___markdown_files
    scripts__check_doc_links__check_links --> scripts__check_doc_links___targets
    scripts__check_doc_links__check_links --> scripts__check_doc_links___resolve
    scripts__check_doc_links__check_links --> scripts__check_doc_links___is_external
    scripts__check_doc_links__main --> scripts__check_doc_links__check_links
    src__nexu__cinema___render_cinema_template --> src__nexu__cinema___cinema_template_text
    src__nexu__cinema__write_cinema_nexu_hooks --> src__nexu__cinema___cinema_template_text
    src__nexu__cinema___contract_to_public_dict --> src__nexu__cinema__format_intract_v1_line
    src__nexu__cinema__build_intract_policy_snapshot --> src__nexu__paths__capsule_dir
    src__nexu__cinema__build_intract_policy_snapshot --> src__nexu__cinema_baseline_contracts__ensure_capsule_intract_yaml
    src__nexu__cinema__build_intract_policy_snapshot --> src__nexu__cinema_baseline_contracts__merge_calculator_baselines
    src__nexu__cinema__build_intract_policy_snapshot --> src__vico__models__read_yaml
    src__nexu__cinema__build_intract_policy_snapshot --> src__nexu__cinema___contract_to_public_dict
    src__nexu__cinema__write_intract_policy_files --> src__nexu__cinema__build_intract_policy_snapshot
    src__nexu__cinema__generate_cinema_player --> src__nexu__paths__capsule_dir
    src__nexu__cinema__generate_cinema_player --> src__nexu__cinema__write_intract_policy_files
    src__nexu__cinema__generate_cinema_player --> src__nexu__cinema__write_cinema_nexu_hooks
    src__nexu__cinema__generate_cinema_player --> src__nexu__cinema_scripts__write_cinema_inject_files
    src__nexu__cinema__generate_cinema_player --> src__nexu__cinema_history__ensure_initial_checkpoint
    src__nexu__cinema__generate_cinema_player --> src__nexu__cinema___render_cinema_template
    src__nexu__cinema___start_cinema_server --> src__nexu__cinema_server__start_cinema_player_server
    src__nexu__cinema_policy___process_ledger_entry --> src__nexu__cinema_policy___process_keep_delete_entries
    src__nexu__cinema_policy___process_ledger_entry --> src__nexu__cinema_policy___process_proposed_contracts
    src__nexu__cinema_policy___process_proposed_contracts --> src__nexu__cinema_policy___proposal_kind_and_element
    src__nexu__cinema_policy__effective_ui_constraints_from_ledger --> src__nexu__cinema_policy___build_constraint_result
    src__nexu__cinema_policy__effective_ui_constraints_from_ledger --> src__nexu__cinema_policy___process_ledger_entry
    src__nexu__cinema_policy___html_files_distinct --> src__nexu__cinema_policy___normalize_html_body
    src__nexu__cinema_policy__option_previews_are_distinct --> src__nexu__cinema_policy___html_files_distinct
    src__nexu__cinema_policy__stage_files_are_distinct --> src__nexu__cinema_policy___html_files_distinct
    src__nexu__cinema_policy__ensure_option_previews_from_stages --> src__nexu__cinema_policy___replace_html_title
    src__nexu__cinema_policy__sync_option_previews_from_workspace --> src__nexu__cinema_scripts__apply_spatial_deletes_to_html
    src__nexu__cinema_policy__sync_option_previews_from_workspace --> src__nexu__cinema_scripts__finalize_cinema_html
    src__nexu__cinema_policy__sync_option_previews_from_workspace --> src__nexu__cinema_policy__load_effective_ui_constraints
    src__nexu__cinema_policy__enforce_deletes_on_option_previews --> src__nexu__cinema_scripts__apply_spatial_deletes_to_html
    src__nexu__cinema_policy__enforce_deletes_on_option_previews --> src__nexu__cinema_scripts__finalize_cinema_html
    src__nexu__cinema_policy__load_effective_ui_constraints --> src__nexu__cinema_policy__policy_ledger_path
    src__nexu__cinema_policy__load_effective_ui_constraints --> src__nexu__cinema_policy__effective_ui_constraints_from_ledger
    src__nexu__cinema_policy__cinema_model_label --> src__nexu__config__load_env_files
    src__nexu__cinema_policy__cinema_model_label --> src__nexu__config__load_config
    src__nexu__cinema_policy__cinema_dir_for --> src__nexu__paths__capsule_dir
    src__nexu__cinema_policy__cinema_dir_for --> src__nexu__paths__project_root
    src__nexu__cinema_policy__policy_snapshot_path --> src__nexu__cinema_policy__cinema_dir_for
    src__nexu__cinema_policy__policy_ledger_path --> src__nexu__cinema_policy__cinema_dir_for
    src__nexu__cinema_policy__load_policy_snapshot --> src__nexu__cinema_policy__policy_snapshot_path
    src__nexu__cinema_policy__manifest_paths_from_snapshot --> src__nexu__paths__project_root
    src__nexu__cinema_policy__apply_ledger_from_cinema --> src__nexu__paths__project_root
    src__nexu__cinema_policy__apply_ledger_from_cinema --> src__nexu__cinema_policy__policy_ledger_path
    src__nexu__cinema_policy__apply_ledger_from_cinema --> src__nexu__cinema_policy__normalize_manifest_target
    src__nexu__cinema_policy__apply_ledger_from_cinema --> src__nexu__cinema_policy__load_policy_snapshot
    src__nexu__cinema_policy__ensure_intract_on_path --> src__nexu__paths__project_root
    src__nexu__cinema_policy__propose_ui_delta_contract_dicts --> src__nexu__cinema_policy__ensure_intract_on_path
    src__nexu__cinema_policy__append_policy_ledger_entry --> src__nexu__cinema_policy__policy_ledger_path
    src__nexu__cinema_policy__normalize_proposals_for_ledger --> src__nexu__cinema_policy___proposal_kind_and_element
    src__nexu__cinema_policy__append_iteration_ledger_entry --> src__nexu__cinema_policy__normalize_proposals_for_ledger
    src__nexu__cinema_policy__append_iteration_ledger_entry --> src__nexu__cinema_policy__append_policy_ledger_entry
    src__nexu__cinema_policy__append_iteration_ledger_entry --> src__nexu__cinema_policy__propose_ui_delta_contract_dicts
    src__nexu__cinema_policy__append_iteration_ledger_entry --> src__nexu__paths__project_root
    src__nexu__cinema_policy__propose_llm_for_stage --> src__nexu__cinema_policy__cinema_dir_for
    src__nexu__cinema_policy__propose_llm_for_stage --> src__nexu__cinema_policy__ensure_intract_on_path
    src__nexu__cinema_policy__propose_llm_for_stage --> src__nexu__cinema_policy__append_policy_ledger_entry
    src__nexu__cinema_policy__propose_llm_for_stage --> src__nexu__paths__project_root
    src__nexu__cinema_policy__validate_intract_artifact --> src__nexu__cinema_policy__ensure_intract_on_path
    src__nexu__cinema_policy__verify_capsule_workspace --> src__nexu__verify__verify_capsule
    src__nexu__cinema_policy__verify_capsule_workspace --> src__nexu__paths__project_root
    src__nexu__cinema_baseline_contracts___contract --> src__nexu__cinema_baseline_contracts___line
    src__nexu__cinema_baseline_contracts__calculator_baseline_contracts --> src__nexu__cinema_baseline_contracts___contract
    src__nexu__cinema_baseline_contracts__is_calculator_capsule --> src__nexu__paths__capsule_dir
    src__nexu__cinema_baseline_contracts__merge_calculator_baselines --> src__nexu__cinema_baseline_contracts__calculator_baseline_contracts
    src__nexu__cinema_baseline_contracts__merge_calculator_baselines --> src__nexu__cinema_baseline_contracts__is_calculator_capsule
    src__nexu__cinema_baseline_contracts__ensure_capsule_intract_yaml --> src__nexu__paths__capsule_dir
    src__nexu__cinema_baseline_contracts__ensure_capsule_intract_yaml --> src__nexu__cinema_baseline_contracts__calculator_baseline_contracts
    src__nexu__cinema_baseline_contracts__ensure_capsule_intract_yaml --> src__nexu__cinema_baseline_contracts__is_calculator_capsule
    src__nexu__cinema_markpact__build_markpact_readme --> src__nexu__cinema_markpact___escape_markdown_fence
    src__nexu__cinema_publish___registry_path --> src__nexu__cinema_publish__services_root
    src__nexu__cinema_publish___load_registry --> src__nexu__cinema_publish___registry_path
    src__nexu__cinema_publish___save_registry --> src__nexu__cinema_publish__services_root
    src__nexu__cinema_publish___save_registry --> src__nexu__cinema_publish___registry_path
    src__nexu__cinema_publish___service_alive --> src__nexu__cinema_publish___port_open
    src__nexu__cinema_publish___service_alive --> src__nexu__cinema_publish___http_ok
    src__nexu__cinema_publish___refresh_service_status --> src__nexu__cinema_publish___service_alive
    src__nexu__cinema_publish__list_published_services --> src__nexu__cinema_publish___load_registry
    src__nexu__cinema_publish__list_published_services --> src__nexu__cinema_publish___save_registry
    src__nexu__cinema_publish__list_published_services --> src__nexu__cinema_publish___refresh_service_status
    src__nexu__cinema_publish___write_service_readme --> src__nexu__cinema_markpact___escape_markdown_fence
    src__nexu__cinema_publish___prepare_service_directory --> src__nexu__cinema_publish__services_root
    src__nexu__cinema_publish___generate_markpact_export --> src__nexu__cinema__build_intract_policy_snapshot
    src__nexu__cinema_publish___generate_markpact_export --> src__nexu__cinema_markpact__build_markpact_readme
    src__nexu__cinema_publish___generate_markpact_export --> src__nexu__cinema_policy__load_effective_ui_constraints
    src__nexu__cinema_publish___allocate_service_port --> src__nexu__cinema_publish___load_registry
    src__nexu__cinema_publish___allocate_service_port --> src__nexu__cinema_publish___pick_port
    src__nexu__cinema_publish___register_service --> src__nexu__cinema_publish___load_registry
    src__nexu__cinema_publish___register_service --> src__nexu__cinema_publish___save_registry
    src__nexu__cinema_publish___handle_existing_service --> src__nexu__cinema_publish___load_registry
    src__nexu__cinema_publish___handle_existing_service --> src__nexu__cinema_publish___service_alive
    src__nexu__cinema_publish___handle_existing_service --> src__nexu__cinema_publish__stop_published_service
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___slug_service_id
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___prepare_service_directory
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema__build_intract_policy_snapshot
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___generate_markpact_export
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___allocate_service_port
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_policy__load_effective_ui_constraints
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___write_service_readme
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___handle_existing_service
    src__nexu__cinema_publish__publish_project_service --> src__nexu__cinema_publish___create_service_entry
    src__nexu__cinema_publish__start_published_service --> src__nexu__cinema_publish___load_registry
    src__nexu__cinema_publish__start_published_service --> src__nexu__cinema_publish___refresh_service_status
    src__nexu__cinema_publish__start_published_service --> src__nexu__cinema_publish___save_registry
    src__nexu__cinema_publish__stop_published_service --> src__nexu__cinema_publish___load_registry
    src__nexu__cinema_publish__stop_published_service --> src__nexu__cinema_publish___save_registry
    src__nexu__cinema_offline_options__is_chemical_goal --> src__nexu__cinema_offline_options___hints_text
    src__nexu__cinema_offline_options___mandatory_trig --> src__nexu__cinema_offline_options___keep_ids_lower
    src__nexu__cinema_offline_options___trig_row --> src__nexu__cinema_offline_options___mandatory_trig
    src__nexu__cinema_offline_options___trig_row --> src__nexu__cinema_offline_options___btn
    src__nexu__cinema_offline_options___trig_row --> src__nexu__cinema_offline_options___keep_ids_lower
    src__nexu__cinema_offline_options___numpad_token_btn --> src__nexu__cinema_offline_options___btn
    src__nexu__cinema_offline_options___numpad_rows --> src__nexu__cinema_offline_options___numpad_token_btn
    src__nexu__cinema_offline_options___numpad_from_policy --> src__nexu__cinema_offline_options___keep_ids_lower
    src__nexu__cinema_offline_options___numpad_from_policy --> src__nexu__cinema_offline_options___numpad_rows
    src__nexu__cinema_offline_options___policy_screen_text --> src__nexu__cinema_offline_options___mandatory_trig
    src__nexu__cinema_offline_options___expanded_excess_row --> src__nexu__cinema_offline_options___keep_ids_lower
    src__nexu__cinema_offline_options___expanded_excess_row --> src__nexu__cinema_offline_options___btn
    src__nexu__cinema_offline_options__build_policy_scientific_option_html --> src__nexu__cinema_offline_options___trig_row
    src__nexu__cinema_offline_options__build_policy_scientific_option_html --> src__nexu__cinema_offline_options___policy_screen_text
    src__nexu__cinema_offline_options__build_policy_scientific_option_html --> src__nexu__cinema_offline_options___expanded_excess_row
    src__nexu__cinema_offline_options__build_policy_scientific_option_html --> src__nexu__cinema_offline_options___option_shell
    src__nexu__cinema_offline_options__build_policy_scientific_option_html --> src__nexu__cinema_offline_options___btn
    src__nexu__cinema_offline_options__build_policy_scientific_option_html --> src__nexu__cinema_offline_options___numpad_from_policy
    src__nexu__cinema_offline_options__build_chemical_option_html --> src__nexu__cinema_offline_options___btn
    src__nexu__cinema_offline_options__build_chemical_option_html --> src__nexu__cinema_offline_options___chemical_shell
    src__nexu__cinema_offline_options__write_goal_options_offline --> src__nexu__cinema_offline_options__is_chemical_goal
    src__nexu__cinema_offline_options__write_goal_options_offline --> src__nexu__cinema_offline_options___policy_constrained
    src__nexu__cinema_offline_options__write_goal_options_offline --> src__nexu__cinema_offline_options___cinema_is_calculator
    src__nexu__cinema_offline_options__write_goal_options_offline --> src__nexu__cinema_scripts__finalize_cinema_html
    src__nexu__cinema_scripts__apply_spatial_deletes_to_html --> src__nexu__cinema_scripts___delete_match_keys
    src__nexu__cinema_scripts__repair_cinema_html_files --> src__nexu__cinema_scripts__write_cinema_inject_files
    src__nexu__cinema_scripts__repair_cinema_html_files --> src__nexu__cinema_scripts__finalize_cinema_html
