flowchart TD
%% generated in 0.01s
    examples__nexu_markpact_exporter["examples.nexu_markpact_exporter<br/>1 funcs"]
    examples__realtime_lane_nexu_sync["examples.realtime_lane_nexu_sync<br/>1 funcs"]
    examples__run_examples["examples.run_examples<br/>2 funcs"]
    examples__scientific_calculator_demo["examples.scientific_calculator_demo<br/>1 funcs"]
    examples__scientific_calculator_demo2["examples.scientific_calculator_demo2<br/>2 funcs"]
    examples__web_app_calculator["examples.web_app_calculator<br/>103 funcs"]
    examples__web_app_dashboard["examples.web_app_dashboard<br/>3 funcs"]
    examples__web_app_event_monitor["examples.web_app_event_monitor<br/>1 funcs"]
    examples__web_app_pactown_ecosystem["examples.web_app_pactown_ecosystem<br/>1 funcs"]
    scripts__check_doc_links["scripts.check-doc-links<br/>8 funcs"]
    scripts__ci_cinema_smoke["scripts.ci-cinema-smoke<br/>1 funcs"]
    src__nexu["src.nexu<br/>456 funcs"]
    src__vico["src.vico<br/>17 funcs"]
    examples__web_app_calculator ==>|92| src__nexu
    src__nexu ==>|53| src__vico
    examples__web_app_pactown_ecosystem ==>|22| scripts__ci_cinema_smoke
    examples__web_app_event_monitor ==>|19| scripts__ci_cinema_smoke
    examples__nexu_markpact_exporter ==>|12| scripts__ci_cinema_smoke
    src__vico ==>|12| src__nexu
    examples__run_examples ==>|11| src__nexu
    examples__web_app_dashboard ==>|10| scripts__ci_cinema_smoke
    examples__scientific_calculator_demo ==>|9| scripts__ci_cinema_smoke
    examples__realtime_lane_nexu_sync ==>|9| scripts__ci_cinema_smoke
    examples__web_app_dashboard ==>|9| src__nexu
    src__nexu ==>|6| examples__web_app_calculator
    examples__scientific_calculator_demo ==>|5| src__nexu
    examples__scientific_calculator_demo2 ==>|4| src__nexu
    examples__web_app_calculator ==>|4| scripts__ci_cinema_smoke
    examples__run_examples -->|3| src__vico
    examples__scientific_calculator_demo2 -->|3| scripts__ci_cinema_smoke
    scripts__check_doc_links -->|3| scripts__ci_cinema_smoke
    src__nexu -->|2| scripts__ci_cinema_smoke
    examples__scientific_calculator_demo -->|1| src__vico
    examples__run_examples -->|1| examples__web_app_calculator
    examples__run_examples -->|1| scripts__ci_cinema_smoke
    examples__scientific_calculator_demo2 -->|1| src__vico
    examples__web_app_calculator -->|1| src__vico
    examples__web_app_dashboard -->|1| src__vico
